version: '3.8'

services:
  redis:
    image: redis:alpine # Use a lightweight Redis image
    container_name: asfinal_redis
    ports:
      - "6379:6379" # Map Codespace port 6379 to container port 6379
    volumes:
      - redis_data:/data # Persist Redis data (optional)

volumes:
  redis_data:
